
---
#If these are left blank, you must pass them as arguments to the script
todo_dir: './todo.txt'
inbox_dir: './'

#Place glob/regex expressions in single quotes.

ignore:
    #Ignore files here.
    - ./gitignore

priorities:
    #Priorities must fit [A-Z], but can otherwise be in any order.
    #If there are mulitple matches present, the highest priority matched will be added.
    Z:
      - '*.zotero'
    C:
      - '*.calibre'
    
projects:
  e-books:
    - '*.epub'
  articles:
    - '*.html'

contexts:
  home:
    - '*.docx'
    - '*.md'
    - '*.html'
  work:
    - '*.html'
