
---
#If these are left blank, you must pass them as arguments to the script
todo_dir: './todo.txt'
inbox_dir: './'

#Place glob/regex expressions in single quotes.

ignore:
    - ./.config
    - ./.git
    - ./venv
    - ./todoignore
    - ./.replit
    - ./replit.nix
    - ./.upm
    - ./poetry.lock
    - ./pyproject.toml
    - ./README.md

projects:
  e-books:
    - '*.epub'
  articles:
    - '*.html'
contexts:
  home:
    - '*.docx'
    - '*.md'
    - '*.html'
  work:
    - '*.html'